### ISSUE TITLE
How to start the game?

### ISSUE THREAD

**Issue by ptrstn** [Ivan-Komlev/Durak#1]
Hi,

Which command/module do I have to execute to launch the application?

Also, what requirements other than ```arcade``` do I need?

When i run ```Durak.py``` I get the following error mesage:

```bash
python Durak.py 
```
```python
1638418234.6399195
Traceback (most recent call last):
  File "/home/ptr/workspace/python/Durak/Durak.py", line 35, in <module>
    theTable.setup()
  File "/home/ptr/workspace/python/Durak/Table.py", line 811, in setup
    self.mixTheDeck()
  File "/home/ptr/workspace/python/Durak/Table.py", line 729, in mixTheDeck
    self.card_list[pos1], self.card_list[pos2] = self.card_list[pos2], self.card_list[pos1]
  File "/home/ptr/workspace/python/Durak/venv/lib/python3.9/site-packages/arcade/sprite_list/sprite_list.py", line 246, in __setitem__
    raise Exception(f"Sprite is already in the list (index {existing_index})")
Exception: Sprite is already in the list (index 34)
```

Thanks!

**Comment by joomlaboat** [comment]
Hi,

The game require "arcade" module.
Install it with this command:
    python -m pip install arcade

Also updated the shuffle method because new Arcade doesn't allow duplicate sprites.
